version: '3'
services:
  csrs1:
    image: mongo:latest
    volumes:
      - ./data/mongodbtest/cs/rs1:/data/db
    command: mongod --noauth --configsvr --replSet csrs --dbpath /data/db
  csrs2:
    image: mongo:latest
    volumes:
      - ./data/mongodbtest/cs/rs2:/data/db
    command: mongod --noauth --configsvr --replSet csrs --dbpath /data/db
  csrs3:
    image: mongo:latest
    volumes:
      - ./data/mongodbtest/cs/rs3:/data/db
    command: mongod --noauth --configsvr --replSet csrs --dbpath /data/db
  mongos:
    image: mongo:latest
    command: mongos --noauth --configdb csrs/csrs1:27019,csrs2:27019,csrs3:27019
  shrs1:
    image: mongo:latest
    volumes:
      - ./data/mongodbtest/sh/rs1:/data/db
    command: mongod --noauth --dbpath /data/db --shardsvr --replSet shrs1
  shrs1-2:
    image: mongo:latest
    volumes:
      - ./data/mongodbtest/sh/rs1-2:/data/db
    command: mongod --noauth --dbpath /data/db --shardsvr --replSet shrs1
  shrs1-3:
    image: mongo:latest
    volumes:
      - ./data/mongodbtest/sh/rs1-3:/data/db
    command: mongod --noauth --dbpath /data/db --shardsvr --replSet shrs1
  shrs2:
    image: mongo:latest
    volumes:
      - ./data/mongodbtest/sh/rs2:/data/db
    command: mongod --noauth --dbpath /data/db --shardsvr --replSet shrs2
  shrs2-2:
    image: mongo:latest
    volumes:
      - ./data/mongodbtest/sh/rs2-2:/data/db
    command: mongod --noauth --dbpath /data/db --shardsvr --replSet shrs2
  shrs2-3:
    image: mongo:latest
    volumes:
      - ./data/mongodbtest/sh/rs2-3:/data/db
    command: mongod --noauth --dbpath /data/db --shardsvr --replSet shrs2
  shrs3:
    image: mongo:latest
    volumes:
      - ./data/mongodbtest/sh/rs3:/data/db
    command: mongod --noauth --dbpath /data/db --shardsvr --replSet shrs3
  shrs3-2:
    image: mongo:latest
    volumes:
      - ./data/mongodbtest/sh/rs3-2:/data/db
    command: mongod --noauth --dbpath /data/db --shardsvr --replSet shrs3
  shrs3-3:
    image: mongo:latest
    volumes:
      - ./data/mongodbtest/sh/rs3-3:/data/db
    command: mongod --noauth --dbpath /data/db --shardsvr --replSet shrs3

